Fix git-commit. git-archive: Generate also .zip: TZ. Improve docs

diff --git a/bin/git-tag b/bin/git-tag
--- a/bin/git-tag
+++ b/bin/git-tag
@@ -18,7 +18,7 @@ Echon() {
 }
 
 EchoExec() {
-	Echo "$*"
+	Echo "# $*"
 	"$@"
 }
 
@@ -32,22 +32,34 @@ Usage() {
 	then	help='
 Create (and optionally sign) a tarball for a release, and sign
 all other tarballs in the directory.
+
 The format of the tarball corresponds to that from github,
 so that you can use the signature file for the release without
 downloading that tarball first: This way, the problem is avoided
-that unsigned data is transferred over the net before signing.'
+that unsigned data is transferred over the net before signing.
+
+Note that to get byte-identical zip files (as necessary for signing),
+the timezone of the generating servers must be identical.
+The script sets the timezone to PST8PDT (of the github servers) by default,
+but you can override this by some options.
+'
+		extraopts='
+-p     Set TZ to ":/usr/share/zoneinfo/US/Pacific-New" for zip file generation
+-P VAL Set TZ to VAL. If VAL is empty or "-", do not modify TZ'
 	else	help='
-Tag a release, reminding about possible signing.
--d Delete tag (locally)
--D Delete tag (locally and remotely)
--r Remove tag (remotely)'
+Tag a release (reminding about possible signing) or remove a tag.'
+		extraopts='
+-d     Delete tag (locally)
+-D     Delete tag (locally and remotely)
+-r     Remove tag (remotely)'
 	fi
 	Echo "Usage: ${0##*/} [options] [tag]$help
--s Sign$signdefault
--a Do not sign$unsigndefault
--t Set GPG_TTY to current tty when signing (default)
--T Do not modify GPG_TTY
--h Show this help"
+-s     Sign$signdefault
+-a     Do not sign$unsigndefault
+-t     Set GPG_TTY to current tty when signing (default)
+-T     Do not modify GPG_TTY$extraopts
+-f     Force even if tag does not start with v
+-h     Show this help"
 	exit ${1:-1}
 }
 
@@ -61,10 +73,11 @@ else	sign=false
 fi
 
 if $archive
-then	addopt=
+then	addopt=pP:
 else	addopt=dDr
 fi
 
+tz=PST8PDT
 gettty=:
 force=false
 delete=false
@@ -74,6 +87,8 @@ while getopts "ftTsahH?$addopt" opt
 do	case $opt in
 	s)	sign=:;;
 	a)	sign=false;;
+	p)	tz=:/usr/share/zoneinfo/US/Pacific-New;;
+	P)	tz=$OPTARG;;
 	d)	delete=:;;
 	D)	delete=:
 		remove=:;;
@@ -96,11 +111,17 @@ fi
 if [ $# -gt 0 ]
 then	tag=$1
 else	EchoExec git tag -ln
+	latesttag=`git describe --abbrev=0 2>/dev/null` || latesttag=
+	if [ -z "${latesttag:++}" ]
+	then	Echo 'Latest tag cannot be determined'
+	else	Echo "$latesttag		(latest tag)"
+	fi
 	if $archive
-	then	Echon 'Enter tag for $tagtext tarball: '
-	else	Echon "Enter new tag $tagtext commit: "
+	then	Echon "Enter tag for $tagtext tarball (default: $latesttag): "
+	else	Echon "Enter new tag for $tagtext commit: "
 	fi
 	read -r tag
+	! $archive || [ -n "${tag:++}" ] || tag=$latesttag
 fi
 
 case ${tag:-/} in
@@ -137,7 +158,14 @@ name=${PWD##*/}
 name=${name%.git}
 n=$name-${tag#v}
 EchoExec git archive --prefix="$n/" -o "$n.tar.gz" "$tag"
-#EchoExec git archive --prefix="$n/" -o "$n.zip" "$tag"
+(
+	[ "${tz:--}" = '-' ] || {
+		TZ=$tz
+		export TZ
+		Echo "# export TZ=\"$tz\""
+	}
+	EchoExec git archive --prefix="$n/" -o "$n.zip" "$tag"
+)
 $sign || exit 0
 
 for i in *.tar *.tar.* *.zip
@@ -148,3 +176,4 @@ do	case $i in
 	test -f "$i" || continue
 	EchoExec gpg --armor --detach-sign "$i"
 done
+:
